///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MertYazilimDesktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MertYazilimDesktopRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c4440b68-3cc0-4846-89dc-2968f202a285")]
    public partial class MertYazilimDesktopRepository : RepoGenBaseFolder
    {
        static MertYazilimDesktopRepository instance = new MertYazilimDesktopRepository();
        MertYazilimDesktopRepositoryFolders.Belge1MicrosoftWordAppFolder _belge1microsoftword;
        MertYazilimDesktopRepositoryFolders.Belge2MicrosoftWordAppFolder _belge2microsoftword;
        MertYazilimDesktopRepositoryFolders.FarklıKaydetAppFolder _farklıkaydet;
        MertYazilimDesktopRepositoryFolders.FormAcAppFolder _formac;
        MertYazilimDesktopRepositoryFolders.MertyazilimMicrosoftWordAppFolder _mertyazilimmicrosoftword;
        MertYazilimDesktopRepositoryFolders.HPBILGISAYARAppFolder _hpbilgisayar;

        /// <summary>
        /// Gets the singleton class instance representing the MertYazilimDesktopRepository element repository.
        /// </summary>
        [RepositoryFolder("c4440b68-3cc0-4846-89dc-2968f202a285")]
        public static MertYazilimDesktopRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MertYazilimDesktopRepository() 
            : base("MertYazilimDesktopRepository", "/", null, 0, false, "c4440b68-3cc0-4846-89dc-2968f202a285", ".\\RepositoryImages\\MertYazilimDesktopRepositoryc4440b68.rximgres")
        {
            _belge1microsoftword = new MertYazilimDesktopRepositoryFolders.Belge1MicrosoftWordAppFolder(this);
            _belge2microsoftword = new MertYazilimDesktopRepositoryFolders.Belge2MicrosoftWordAppFolder(this);
            _farklıkaydet = new MertYazilimDesktopRepositoryFolders.FarklıKaydetAppFolder(this);
            _formac = new MertYazilimDesktopRepositoryFolders.FormAcAppFolder(this);
            _mertyazilimmicrosoftword = new MertYazilimDesktopRepositoryFolders.MertyazilimMicrosoftWordAppFolder(this);
            _hpbilgisayar = new MertYazilimDesktopRepositoryFolders.HPBILGISAYARAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c4440b68-3cc0-4846-89dc-2968f202a285")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Belge1MicrosoftWord folder.
        /// </summary>
        [RepositoryFolder("8eaa4670-017d-49a0-8149-e832500f7ceb")]
        public virtual MertYazilimDesktopRepositoryFolders.Belge1MicrosoftWordAppFolder Belge1MicrosoftWord
        {
            get { return _belge1microsoftword; }
        }

        /// <summary>
        /// The Belge2MicrosoftWord folder.
        /// </summary>
        [RepositoryFolder("e4f09143-e02a-496e-9aa9-096b7a83dd0c")]
        public virtual MertYazilimDesktopRepositoryFolders.Belge2MicrosoftWordAppFolder Belge2MicrosoftWord
        {
            get { return _belge2microsoftword; }
        }

        /// <summary>
        /// The FarklıKaydet folder.
        /// </summary>
        [RepositoryFolder("1f990655-5cdf-4f97-b40c-f658e19136ba")]
        public virtual MertYazilimDesktopRepositoryFolders.FarklıKaydetAppFolder FarklıKaydet
        {
            get { return _farklıkaydet; }
        }

        /// <summary>
        /// The FormAc folder.
        /// </summary>
        [RepositoryFolder("9264929a-381f-40c3-9dd9-2c37a44e8e84")]
        public virtual MertYazilimDesktopRepositoryFolders.FormAcAppFolder FormAc
        {
            get { return _formac; }
        }

        /// <summary>
        /// The MertyazilimMicrosoftWord folder.
        /// </summary>
        [RepositoryFolder("7782805e-eff8-4427-9ae3-e2009eb1c150")]
        public virtual MertYazilimDesktopRepositoryFolders.MertyazilimMicrosoftWordAppFolder MertyazilimMicrosoftWord
        {
            get { return _mertyazilimmicrosoftword; }
        }

        /// <summary>
        /// The HPBILGISAYAR folder.
        /// </summary>
        [RepositoryFolder("7344f02c-483d-4a83-bba2-a311edfd4375")]
        public virtual MertYazilimDesktopRepositoryFolders.HPBILGISAYARAppFolder HPBILGISAYAR
        {
            get { return _hpbilgisayar; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MertYazilimDesktopRepositoryFolders
    {
        /// <summary>
        /// The Belge1MicrosoftWordAppFolder folder.
        /// </summary>
        [RepositoryFolder("8eaa4670-017d-49a0-8149-e832500f7ceb")]
        public partial class Belge1MicrosoftWordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _filetabbuttonInfo;
            RepoItemInfo _yeniInfo;
            RepoItemInfo _boşbelgeInfo;

            /// <summary>
            /// Creates a new Belge1MicrosoftWord  folder.
            /// </summary>
            public Belge1MicrosoftWordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Belge1MicrosoftWord", "/form[@title='Belge1 - Microsoft Word']", parentFolder, 30000, null, true, "8eaa4670-017d-49a0-8149-e832500f7ceb", "")
            {
                _filetabbuttonInfo = new RepoItemInfo(this, "FileTabButton", "container[@caption='MsoDockTop']/container[@caption='Ribbon']//container[@name='Ribbon']/button[@automationid='FileTabButton']", ".//button[@automationid='FileTabButton']", 30000, null, "93cee34b-82af-49ca-a0a0-f52f9d56a92a");
                _yeniInfo = new RepoItemInfo(this, "Yeni", ".//container[@automationid='BackstageView']/contextmenu[@automationid='NavBarMenu']/tabpage[@name='Yeni']", ".//tabpage[@name='Yeni']", 30000, null, "9e157199-bf2d-407c-9993-34bdcaac4cf8");
                _boşbelgeInfo = new RepoItemInfo(this, "BoşBelge", ".//container[@automationid='BackstageView']/container[@name='Yeni']/?/?/container[@classname='NetUIScrollViewer']/table[1]/listitem[@name='Boş belge']", ".//listitem[@name='Boş belge']", 30000, null, "0de46d74-6cdc-4ae5-a46a-34add7e2caec");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8eaa4670-017d-49a0-8149-e832500f7ceb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8eaa4670-017d-49a0-8149-e832500f7ceb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FileTabButton item.
            /// </summary>
            [RepositoryItem("93cee34b-82af-49ca-a0a0-f52f9d56a92a")]
            public virtual Ranorex.Button FileTabButton
            {
                get
                {
                    return _filetabbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FileTabButton item info.
            /// </summary>
            [RepositoryItemInfo("93cee34b-82af-49ca-a0a0-f52f9d56a92a")]
            public virtual RepoItemInfo FileTabButtonInfo
            {
                get
                {
                    return _filetabbuttonInfo;
                }
            }

            /// <summary>
            /// The Yeni item.
            /// </summary>
            [RepositoryItem("9e157199-bf2d-407c-9993-34bdcaac4cf8")]
            public virtual Ranorex.TabPage Yeni
            {
                get
                {
                    return _yeniInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The Yeni item info.
            /// </summary>
            [RepositoryItemInfo("9e157199-bf2d-407c-9993-34bdcaac4cf8")]
            public virtual RepoItemInfo YeniInfo
            {
                get
                {
                    return _yeniInfo;
                }
            }

            /// <summary>
            /// The BoşBelge item.
            /// </summary>
            [RepositoryItem("0de46d74-6cdc-4ae5-a46a-34add7e2caec")]
            public virtual Ranorex.ListItem BoşBelge
            {
                get
                {
                    return _boşbelgeInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The BoşBelge item info.
            /// </summary>
            [RepositoryItemInfo("0de46d74-6cdc-4ae5-a46a-34add7e2caec")]
            public virtual RepoItemInfo BoşBelgeInfo
            {
                get
                {
                    return _boşbelgeInfo;
                }
            }
        }

        /// <summary>
        /// The Belge2MicrosoftWordAppFolder folder.
        /// </summary>
        [RepositoryFolder("e4f09143-e02a-496e-9aa9-096b7a83dd0c")]
        public partial class Belge2MicrosoftWordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _kaydetInfo;
            RepoItemInfo _filetabbuttonInfo;
            RepoItemInfo _menuitemacInfo;
            RepoItemInfo _buttonbulInfo;
            RepoItemInfo _mertyazilimdocxInfo;
            RepoItemInfo _kalınInfo;

            /// <summary>
            /// Creates a new Belge2MicrosoftWord  folder.
            /// </summary>
            public Belge2MicrosoftWordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Belge2MicrosoftWord", "/form[@title='Belge2 - Microsoft Word']", parentFolder, 30000, null, true, "e4f09143-e02a-496e-9aa9-096b7a83dd0c", "")
            {
                _kaydetInfo = new RepoItemInfo(this, "Kaydet", "container[@caption='MsoDockTop']//container[@name='Ribbon']/toolbar[@name='Hızlı Erişim Araç Çubuğu']/button[@name='Kaydet']", ".//button[@name='Kaydet']", 30000, null, "4e331e80-9d10-44ee-9e52-8b3e60ec2704");
                _filetabbuttonInfo = new RepoItemInfo(this, "FileTabButton", "container[@caption='MsoDockTop']/container[@caption='Ribbon']//container[@name='Ribbon']/button[@automationid='FileTabButton']", ".//button[@automationid='FileTabButton']", 30000, null, "b8c321db-b755-4644-8a5c-85529d712434");
                _menuitemacInfo = new RepoItemInfo(this, "MenuItemAc", ".//container[@automationid='BackstageView']/contextmenu[@automationid='NavBarMenu']/menuitem[@name='Aç']", ".//menuitem[@name='Aç']", 30000, null, "23ce56e2-0834-4255-a231-af787479710c");
                _buttonbulInfo = new RepoItemInfo(this, "ButtonBul", ".//container[@name='Ribbon']/container[@name='Alt Şerit']/element[@name='Giriş']/container[@name='Düzenleme']/button[@name='Bul']/button[@name='Bul']", ".//button[@acceleratorkey='Ctrl+F']", 30000, null, "c550495f-d510-4fc5-8b2d-f62c2c27f9c4");
                _mertyazilimdocxInfo = new RepoItemInfo(this, "MertyazilimDocx", "element[@class='_WwF']/?/?/worddoc[@name='mertyazilim.docx']", ".//worddoc[@name='mertyazilim.docx']", 30000, null, "747e35f5-74ca-4a46-90d9-0ac0d1ada735");
                _kalınInfo = new RepoItemInfo(this, "Kalın", ".//container[@name='Ribbon']/container[@name='Alt Şerit']/element[@name='Giriş']/container[@name='Yazı Tipi']/button[@name='Kalın']", ".//button[@name='Kalın']", 30000, null, "54440952-d43f-469e-92f0-8e6e6a2349bc");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e4f09143-e02a-496e-9aa9-096b7a83dd0c")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e4f09143-e02a-496e-9aa9-096b7a83dd0c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Kaydet item.
            /// </summary>
            [RepositoryItem("4e331e80-9d10-44ee-9e52-8b3e60ec2704")]
            public virtual Ranorex.Button Kaydet
            {
                get
                {
                    return _kaydetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kaydet item info.
            /// </summary>
            [RepositoryItemInfo("4e331e80-9d10-44ee-9e52-8b3e60ec2704")]
            public virtual RepoItemInfo KaydetInfo
            {
                get
                {
                    return _kaydetInfo;
                }
            }

            /// <summary>
            /// The FileTabButton item.
            /// </summary>
            [RepositoryItem("b8c321db-b755-4644-8a5c-85529d712434")]
            public virtual Ranorex.Button FileTabButton
            {
                get
                {
                    return _filetabbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The FileTabButton item info.
            /// </summary>
            [RepositoryItemInfo("b8c321db-b755-4644-8a5c-85529d712434")]
            public virtual RepoItemInfo FileTabButtonInfo
            {
                get
                {
                    return _filetabbuttonInfo;
                }
            }

            /// <summary>
            /// The MenuItemAc item.
            /// </summary>
            [RepositoryItem("23ce56e2-0834-4255-a231-af787479710c")]
            public virtual Ranorex.MenuItem MenuItemAc
            {
                get
                {
                    return _menuitemacInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The MenuItemAc item info.
            /// </summary>
            [RepositoryItemInfo("23ce56e2-0834-4255-a231-af787479710c")]
            public virtual RepoItemInfo MenuItemAcInfo
            {
                get
                {
                    return _menuitemacInfo;
                }
            }

            /// <summary>
            /// The ButtonBul item.
            /// </summary>
            [RepositoryItem("c550495f-d510-4fc5-8b2d-f62c2c27f9c4")]
            public virtual Ranorex.Button ButtonBul
            {
                get
                {
                    return _buttonbulInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonBul item info.
            /// </summary>
            [RepositoryItemInfo("c550495f-d510-4fc5-8b2d-f62c2c27f9c4")]
            public virtual RepoItemInfo ButtonBulInfo
            {
                get
                {
                    return _buttonbulInfo;
                }
            }

            /// <summary>
            /// The MertyazilimDocx item.
            /// </summary>
            [RepositoryItem("747e35f5-74ca-4a46-90d9-0ac0d1ada735")]
            public virtual Ranorex.WordDocument MertyazilimDocx
            {
                get
                {
                    return _mertyazilimdocxInfo.CreateAdapter<Ranorex.WordDocument>(true);
                }
            }

            /// <summary>
            /// The MertyazilimDocx item info.
            /// </summary>
            [RepositoryItemInfo("747e35f5-74ca-4a46-90d9-0ac0d1ada735")]
            public virtual RepoItemInfo MertyazilimDocxInfo
            {
                get
                {
                    return _mertyazilimdocxInfo;
                }
            }

            /// <summary>
            /// The Kalın item.
            /// </summary>
            [RepositoryItem("54440952-d43f-469e-92f0-8e6e6a2349bc")]
            public virtual Ranorex.Button Kalın
            {
                get
                {
                    return _kalınInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kalın item info.
            /// </summary>
            [RepositoryItemInfo("54440952-d43f-469e-92f0-8e6e6a2349bc")]
            public virtual RepoItemInfo KalınInfo
            {
                get
                {
                    return _kalınInfo;
                }
            }
        }

        /// <summary>
        /// The FarklıKaydetAppFolder folder.
        /// </summary>
        [RepositoryFolder("1f990655-5cdf-4f97-b40c-f658e19136ba")]
        public partial class FarklıKaydetAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _masauestueInfo;
            RepoItemInfo _text1001Info;
            RepoItemInfo _kaydetInfo;

            /// <summary>
            /// Creates a new FarklıKaydet  folder.
            /// </summary>
            public FarklıKaydetAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FarklıKaydet", "/form[@title='Farklı Kaydet']", parentFolder, 30000, null, true, "1f990655-5cdf-4f97-b40c-f658e19136ba", "")
            {
                _masauestueInfo = new RepoItemInfo(this, "Masauestue", "element[@class='DUIViewWndClassName']/container/element[2]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Masaüstü']", ".//tree[@controlid='100']/treeitem[@text='Sık Kullanılanlar']/treeitem[@text='Masaüstü']", 30000, null, "da392d2c-023c-40f8-8931-f7aae0f93b24");
                _text1001Info = new RepoItemInfo(this, "Text1001", "?/?/container[@class='DirectUIHWND']/element[9]/combobox[@class='ComboBox']/text[@controlid='1001']", ".//text[@controlid='1001']", 30000, null, "86e8c925-35ea-404a-9d0a-627046529b10");
                _kaydetInfo = new RepoItemInfo(this, "Kaydet", "button[@text='Kay&det']", "button[@text='Kay&det']", 30000, null, "f3635ceb-3f73-494c-8813-fbacca608f66");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1f990655-5cdf-4f97-b40c-f658e19136ba")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1f990655-5cdf-4f97-b40c-f658e19136ba")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Masauestue item.
            /// </summary>
            [RepositoryItem("da392d2c-023c-40f8-8931-f7aae0f93b24")]
            public virtual Ranorex.TreeItem Masauestue
            {
                get
                {
                    return _masauestueInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Masauestue item info.
            /// </summary>
            [RepositoryItemInfo("da392d2c-023c-40f8-8931-f7aae0f93b24")]
            public virtual RepoItemInfo MasauestueInfo
            {
                get
                {
                    return _masauestueInfo;
                }
            }

            /// <summary>
            /// The Text1001 item.
            /// </summary>
            [RepositoryItem("86e8c925-35ea-404a-9d0a-627046529b10")]
            public virtual Ranorex.Text Text1001
            {
                get
                {
                    return _text1001Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1001 item info.
            /// </summary>
            [RepositoryItemInfo("86e8c925-35ea-404a-9d0a-627046529b10")]
            public virtual RepoItemInfo Text1001Info
            {
                get
                {
                    return _text1001Info;
                }
            }

            /// <summary>
            /// The Kaydet item.
            /// </summary>
            [RepositoryItem("f3635ceb-3f73-494c-8813-fbacca608f66")]
            public virtual Ranorex.Button Kaydet
            {
                get
                {
                    return _kaydetInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Kaydet item info.
            /// </summary>
            [RepositoryItemInfo("f3635ceb-3f73-494c-8813-fbacca608f66")]
            public virtual RepoItemInfo KaydetInfo
            {
                get
                {
                    return _kaydetInfo;
                }
            }
        }

        /// <summary>
        /// The FormAcAppFolder folder.
        /// </summary>
        [RepositoryFolder("9264929a-381f-40c3-9dd9-2c37a44e8e84")]
        public partial class FormAcAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _masauestueInfo;
            RepoItemInfo _someindicatorInfo;
            RepoItemInfo _uiimageInfo;
            RepoItemInfo _buttonacInfo;

            /// <summary>
            /// Creates a new FormAc  folder.
            /// </summary>
            public FormAcAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormAc", "/form[@title='Aç']", parentFolder, 30000, null, true, "9264929a-381f-40c3-9dd9-2c37a44e8e84", "")
            {
                _masauestueInfo = new RepoItemInfo(this, "Masauestue", "element[@class='DUIViewWndClassName']/container/element[1]/?/?/tree[@controlid='100']/?/?/treeitem[@text='Masaüstü']", ".//tree[@controlid='100']/treeitem[@text='Sık Kullanılanlar']/treeitem[@text='Masaüstü']", 30000, null, "026a1b07-592b-4302-b5d2-1b24800feac0");
                _someindicatorInfo = new RepoItemInfo(this, "SomeIndicator", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/element[@instance='0']/scrollbar[@style='Custom']/indicator", ".//container[@caption='ShellView']/container[@class='DirectUIHWND']/element[@instance='0']/scrollbar[@style='Custom']/indicator", 30000, null, "490e516f-b264-4a3e-9428-2009dcfde8e3");
                _uiimageInfo = new RepoItemInfo(this, "UIImage", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='7']/picture[@classname='UIImage']", ".//listitem[@automationid='7']/picture[@classname='UIImage']", 30000, null, "6649aa90-312f-4f53-8840-1dc63dfaccad");
                _buttonacInfo = new RepoItemInfo(this, "ButtonAc", "button[@text='&Aç']", "button[@text='&Aç']", 30000, null, "ce2124db-774b-4190-8b09-f5dfacf0eb2c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9264929a-381f-40c3-9dd9-2c37a44e8e84")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9264929a-381f-40c3-9dd9-2c37a44e8e84")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Masauestue item.
            /// </summary>
            [RepositoryItem("026a1b07-592b-4302-b5d2-1b24800feac0")]
            public virtual Ranorex.TreeItem Masauestue
            {
                get
                {
                    return _masauestueInfo.CreateAdapter<Ranorex.TreeItem>(true);
                }
            }

            /// <summary>
            /// The Masauestue item info.
            /// </summary>
            [RepositoryItemInfo("026a1b07-592b-4302-b5d2-1b24800feac0")]
            public virtual RepoItemInfo MasauestueInfo
            {
                get
                {
                    return _masauestueInfo;
                }
            }

            /// <summary>
            /// The SomeIndicator item.
            /// </summary>
            [RepositoryItem("490e516f-b264-4a3e-9428-2009dcfde8e3")]
            public virtual Ranorex.Indicator SomeIndicator
            {
                get
                {
                    return _someindicatorInfo.CreateAdapter<Ranorex.Indicator>(true);
                }
            }

            /// <summary>
            /// The SomeIndicator item info.
            /// </summary>
            [RepositoryItemInfo("490e516f-b264-4a3e-9428-2009dcfde8e3")]
            public virtual RepoItemInfo SomeIndicatorInfo
            {
                get
                {
                    return _someindicatorInfo;
                }
            }

            /// <summary>
            /// The UIImage item.
            /// </summary>
            [RepositoryItem("6649aa90-312f-4f53-8840-1dc63dfaccad")]
            public virtual Ranorex.Picture UIImage
            {
                get
                {
                    return _uiimageInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The UIImage item info.
            /// </summary>
            [RepositoryItemInfo("6649aa90-312f-4f53-8840-1dc63dfaccad")]
            public virtual RepoItemInfo UIImageInfo
            {
                get
                {
                    return _uiimageInfo;
                }
            }

            /// <summary>
            /// The ButtonAc item.
            /// </summary>
            [RepositoryItem("ce2124db-774b-4190-8b09-f5dfacf0eb2c")]
            public virtual Ranorex.Button ButtonAc
            {
                get
                {
                    return _buttonacInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAc item info.
            /// </summary>
            [RepositoryItemInfo("ce2124db-774b-4190-8b09-f5dfacf0eb2c")]
            public virtual RepoItemInfo ButtonAcInfo
            {
                get
                {
                    return _buttonacInfo;
                }
            }
        }

        /// <summary>
        /// The MertyazilimMicrosoftWordAppFolder folder.
        /// </summary>
        [RepositoryFolder("7782805e-eff8-4427-9ae3-e2009eb1c150")]
        public partial class MertyazilimMicrosoftWordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _belgearaInfo;

            /// <summary>
            /// Creates a new MertyazilimMicrosoftWord  folder.
            /// </summary>
            public MertyazilimMicrosoftWordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MertyazilimMicrosoftWord", "/form[@title>'mertyazilim - Microsoft W']", parentFolder, 30000, null, true, "7782805e-eff8-4427-9ae3-e2009eb1c150", "")
            {
                _belgearaInfo = new RepoItemInfo(this, "BelgeAra", "container[@caption='MsoDockLeft']/container[@caption='Gezinti']//element[@class='NetUICtrlNotifySink']/?/?/text[@accessiblename='Belge Ara']", ".//text[@accessiblename='Belge Ara']", 30000, null, "52202dd4-8dd5-4e3a-92d8-0a24f9b14dae");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7782805e-eff8-4427-9ae3-e2009eb1c150")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7782805e-eff8-4427-9ae3-e2009eb1c150")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The BelgeAra item.
            /// </summary>
            [RepositoryItem("52202dd4-8dd5-4e3a-92d8-0a24f9b14dae")]
            public virtual Ranorex.Text BelgeAra
            {
                get
                {
                    return _belgearaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The BelgeAra item info.
            /// </summary>
            [RepositoryItemInfo("52202dd4-8dd5-4e3a-92d8-0a24f9b14dae")]
            public virtual RepoItemInfo BelgeAraInfo
            {
                get
                {
                    return _belgearaInfo;
                }
            }
        }

        /// <summary>
        /// The HPBILGISAYARAppFolder folder.
        /// </summary>
        [RepositoryFolder("7344f02c-483d-4a83-bba2-a311edfd4375")]
        public partial class HPBILGISAYARAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _hpbilgisayarInfo;

            /// <summary>
            /// Creates a new HPBILGISAYAR  folder.
            /// </summary>
            public HPBILGISAYARAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HPBILGISAYAR", "", parentFolder, 30000, null, true, "7344f02c-483d-4a83-bba2-a311edfd4375", "")
            {
                _hpbilgisayarInfo = new RepoItemInfo(this, "HPBILGISAYAR", "", "", 30000, null, "b143ef56-e1e5-49a1-9c2d-4707111f8e0e");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("7344f02c-483d-4a83-bba2-a311edfd4375")]
            public virtual Ranorex.Host Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Host>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("7344f02c-483d-4a83-bba2-a311edfd4375")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The HPBILGISAYAR item.
            /// </summary>
            [RepositoryItem("b143ef56-e1e5-49a1-9c2d-4707111f8e0e")]
            public virtual Ranorex.Host HPBILGISAYAR
            {
                get
                {
                    return _hpbilgisayarInfo.CreateAdapter<Ranorex.Host>(true);
                }
            }

            /// <summary>
            /// The HPBILGISAYAR item info.
            /// </summary>
            [RepositoryItemInfo("b143ef56-e1e5-49a1-9c2d-4707111f8e0e")]
            public virtual RepoItemInfo HPBILGISAYARInfo
            {
                get
                {
                    return _hpbilgisayarInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
