///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MertYazilimDesktop
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("8a068618-b1ab-4b1d-b7bc-43d24940f527", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MertYazilimDesktopRepository repository.
        /// </summary>
        public static MertYazilimDesktopRepository repo = MertYazilimDesktopRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge1MicrosoftWord.FileTabButton' at 30;14.", repo.Belge1MicrosoftWord.FileTabButtonInfo, new RecordItemIndex(0));
            repo.Belge1MicrosoftWord.FileTabButton.Click("30;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge1MicrosoftWord.Yeni' at 57;9.", repo.Belge1MicrosoftWord.YeniInfo, new RecordItemIndex(1));
            repo.Belge1MicrosoftWord.Yeni.Click("57;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Belge1MicrosoftWord.BoşBelge' at 42;63.", repo.Belge1MicrosoftWord.BoşBelgeInfo, new RecordItemIndex(2));
            repo.Belge1MicrosoftWord.BoşBelge.DoubleClick("42;63");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'deneme olarak yapılmıştır' with focus on 'Belge2MicrosoftWord'.", repo.Belge2MicrosoftWord.SelfInfo, new RecordItemIndex(3));
            repo.Belge2MicrosoftWord.Self.EnsureVisible();
            Keyboard.Press("deneme olarak yapılmıştır");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.Kaydet' at 6;10.", repo.Belge2MicrosoftWord.KaydetInfo, new RecordItemIndex(4));
            repo.Belge2MicrosoftWord.Kaydet.Click("6;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FarklıKaydet.Masauestue' at 25;13.", repo.FarklıKaydet.MasauestueInfo, new RecordItemIndex(5));
            repo.FarklıKaydet.Masauestue.Click("25;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FarklıKaydet.Text1001' at 178;8.", repo.FarklıKaydet.Text1001Info, new RecordItemIndex(6));
            repo.FarklıKaydet.Text1001.Click("178;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'mert' with focus on 'FarklıKaydet.Text1001'.", repo.FarklıKaydet.Text1001Info, new RecordItemIndex(7));
            repo.FarklıKaydet.Text1001.PressKeys("mert");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'yazilim' with focus on 'FarklıKaydet.Text1001'.", repo.FarklıKaydet.Text1001Info, new RecordItemIndex(8));
            repo.FarklıKaydet.Text1001.PressKeys("yazilim");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FarklıKaydet.Kaydet' at 40;8.", repo.FarklıKaydet.KaydetInfo, new RecordItemIndex(9));
            repo.FarklıKaydet.Kaydet.Click("40;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.FileTabButton' at 26;11.", repo.Belge2MicrosoftWord.FileTabButtonInfo, new RecordItemIndex(10));
            repo.Belge2MicrosoftWord.FileTabButton.Click("26;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.MenuItemAc' at 49;14.", repo.Belge2MicrosoftWord.MenuItemAcInfo, new RecordItemIndex(11));
            repo.Belge2MicrosoftWord.MenuItemAc.Click("49;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormAc.Masauestue' at 24;10.", repo.FormAc.MasauestueInfo, new RecordItemIndex(12));
            repo.FormAc.Masauestue.Click("24;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FormAc.SomeIndicator' at 5;61.", repo.FormAc.SomeIndicatorInfo, new RecordItemIndex(13));
            repo.FormAc.SomeIndicator.MoveTo("5;61");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'FormAc.SomeIndicator' at 4;157.", repo.FormAc.SomeIndicatorInfo, new RecordItemIndex(14));
            repo.FormAc.SomeIndicator.MoveTo("4;157");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormAc.UIImage' at 45;18.", repo.FormAc.UIImageInfo, new RecordItemIndex(15));
            repo.FormAc.UIImage.Click("45;18");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormAc.ButtonAc' at 36;14.", repo.FormAc.ButtonAcInfo, new RecordItemIndex(16));
            repo.FormAc.ButtonAc.Click("36;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.ButtonBul' at 29;10.", repo.Belge2MicrosoftWord.ButtonBulInfo, new RecordItemIndex(17));
            repo.Belge2MicrosoftWord.ButtonBul.Click("29;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MertyazilimMicrosoftWord.BelgeAra' at 80;7.", repo.MertyazilimMicrosoftWord.BelgeAraInfo, new RecordItemIndex(18));
            repo.MertyazilimMicrosoftWord.BelgeAra.Click("80;7");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'deneme' with focus on 'MertyazilimMicrosoftWord.BelgeAra'.", repo.MertyazilimMicrosoftWord.BelgeAraInfo, new RecordItemIndex(19));
            repo.MertyazilimMicrosoftWord.BelgeAra.PressKeys("deneme");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.MertyazilimDocx' at 92;104.", repo.Belge2MicrosoftWord.MertyazilimDocxInfo, new RecordItemIndex(20));
            repo.Belge2MicrosoftWord.MertyazilimDocx.Click("92;104");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'Belge2MicrosoftWord.MertyazilimDocx' at 126;99.", repo.Belge2MicrosoftWord.MertyazilimDocxInfo, new RecordItemIndex(21));
            repo.Belge2MicrosoftWord.MertyazilimDocx.DoubleClick("126;99");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'Belge2MicrosoftWord.MertyazilimDocx' at 126;99.", repo.Belge2MicrosoftWord.MertyazilimDocxInfo, new RecordItemIndex(22));
            repo.Belge2MicrosoftWord.MertyazilimDocx.MoveTo("126;99");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'Belge2MicrosoftWord.MertyazilimDocx' at 111;83.", repo.Belge2MicrosoftWord.MertyazilimDocxInfo, new RecordItemIndex(23));
            repo.Belge2MicrosoftWord.MertyazilimDocx.MoveTo("111;83");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.Kalın' at 11;9.", repo.Belge2MicrosoftWord.KalınInfo, new RecordItemIndex(24));
            repo.Belge2MicrosoftWord.Kalın.Click("11;9");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Belge2MicrosoftWord.Kalın' at 11;9.", repo.Belge2MicrosoftWord.KalınInfo, new RecordItemIndex(25));
            repo.Belge2MicrosoftWord.Kalın.Click("11;9");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
